version: "2.1"

services:
  grafana_agent:
    container_name: grafana_agent
    image: grafana/agent:v0.30.1
    ports:
      - "3500:3500"
      - "4317:4317"
    volumes:
      - "${PWD}/grafana-agent/agent.yaml:/etc/agent/agent.yaml"
    command: [
      "-config.file=/etc/agent/agent.yaml",
      "-config.expand-env",
    ]
    env_file:
      .env